/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Categorias;
import Models.Departamentos;
import ViewModels.CategoriaVM;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author avice
 */
public class CategoriasForm extends javax.swing.JInternalFrame {

    private CategoriaVM categoria;
    private String accion = "insert";
    /**
     * Creates new form CategoriasForm
     */
    public CategoriasForm() {
        initComponents();
        this.getContentPane().setBackground(new Color(93, 188, 210));

        ArrayList<JLabel> label = new ArrayList();
        label.add(lblDescripcion);
        label.add(lblCategoria);

        ArrayList<JTextField> textfield = new ArrayList();
        textfield.add(txtDepartamento);
        textfield.add(txtCategoria);
        textfield.add(txtBuscar);

        Object[] objects = {
            rbtDpt,
            rbtCat,
            tblDepartamentos,
            tblCategorias
        };
        
        categoria = new CategoriaVM(objects, label, textfield);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias =  tblCategorias = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jPanel15 = new javax.swing.JPanel();
        rbtDpt = new javax.swing.JRadioButton();
        rbtCat = new javax.swing.JRadioButton();
        Button_GuardarCatDpt = new javax.swing.JButton();
        Button_EliminarCatDpt = new javax.swing.JButton();
        Button_CancelarCatDpt = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        lblDescripcion1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDepartamentos =  tblDepartamentos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };

        setBackground(new java.awt.Color(93, 188, 210));
        setClosable(true);
        setIconifiable(true);
        setTitle("Departamentos  / Categorias");

        jPanel1.setBackground(new java.awt.Color(226, 236, 248));

        jPanel3.setBackground(new java.awt.Color(233, 240, 248));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblCategorias.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriasMouseClicked(evt);
            }
        });
        tblCategorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCategoriasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategorias);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel15.setBackground(new java.awt.Color(233, 240, 248));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        rbtDpt.setBackground(new java.awt.Color(255, 255, 255));
        rbtDpt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtDpt.setForeground(new java.awt.Color(0, 153, 51));
        rbtDpt.setSelected(true);
        rbtDpt.setText("Departamento");
        rbtDpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDptActionPerformed(evt);
            }
        });

        rbtCat.setBackground(new java.awt.Color(255, 255, 255));
        rbtCat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtCat.setForeground(new java.awt.Color(70, 106, 124));
        rbtCat.setText("Categoria");
        rbtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCatActionPerformed(evt);
            }
        });

        Button_GuardarCatDpt.setBackground(new java.awt.Color(59, 69, 97));
        Button_GuardarCatDpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-guardar-40.png"))); // NOI18N
        Button_GuardarCatDpt.setToolTipText("Guardar");
        Button_GuardarCatDpt.setBorder(null);
        Button_GuardarCatDpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarCatDptActionPerformed(evt);
            }
        });

        Button_EliminarCatDpt.setBackground(new java.awt.Color(59, 69, 97));
        Button_EliminarCatDpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-eliminar-32.png"))); // NOI18N
        Button_EliminarCatDpt.setToolTipText("Eliminar");
        Button_EliminarCatDpt.setBorder(null);
        Button_EliminarCatDpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EliminarCatDptActionPerformed(evt);
            }
        });

        Button_CancelarCatDpt.setBackground(new java.awt.Color(59, 69, 97));
        Button_CancelarCatDpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-cancelar-2-32.png"))); // NOI18N
        Button_CancelarCatDpt.setToolTipText("Cancelar");
        Button_CancelarCatDpt.setBorder(null);
        Button_CancelarCatDpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarCatDptActionPerformed(evt);
            }
        });

        jPanel22.setBackground(new java.awt.Color(233, 240, 248));
        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCategoria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(70, 106, 124));
        lblCategoria.setText("Categoria");
        lblCategoria.setToolTipText("");

        txtCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoriaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtCategoria))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel23.setBackground(new java.awt.Color(233, 240, 248));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(70, 106, 124));
        lblDescripcion.setText("Departamento");
        lblDescripcion.setToolTipText("");

        txtDepartamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDepartamentoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDepartamento))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(Button_GuardarCatDpt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_EliminarCatDpt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_CancelarCatDpt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(rbtDpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rbtCat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtDpt)
                    .addComponent(rbtCat))
                .addGap(18, 18, 18)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_GuardarCatDpt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_EliminarCatDpt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CancelarCatDpt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        lblDescripcion1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDescripcion1.setText("Buscar");

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(233, 240, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblDepartamentos.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        tblDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDepartamentosMouseClicked(evt);
            }
        });
        tblDepartamentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDepartamentosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblDepartamentos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(381, 381, 381))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCategoriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCategoriasKeyReleased
        if (tblCategorias.getSelectedRows().length > 0) {
            categoria.datosCategoria();
        }
    }//GEN-LAST:event_tblCategoriasKeyReleased

    private void tblCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriasMouseClicked
        if (tblCategorias.getSelectedRows().length > 0) {
            categoria.datosCategoria();
        }
    }//GEN-LAST:event_tblCategoriasMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
//        categoria.searchCategoria(txtBuscar.getText());
//        categoria.crearTabla();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void rbtDptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDptActionPerformed
        txtCategoria.setEnabled(false);
        txtDepartamento.setEnabled(true);
        rbtDpt.setForeground(new Color(0, 153, 51));
        rbtCat.setForeground(new Color(70, 106, 124));
        rbtCat.setSelected(false);
        txtCategoria.setText("");
        txtDepartamento.requestFocus();
    }//GEN-LAST:event_rbtDptActionPerformed

    private void rbtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCatActionPerformed
        txtCategoria.setEnabled(true);
        txtDepartamento.setEnabled(false);
        rbtDpt.setForeground(new Color(70, 106, 124));
        rbtCat.setForeground(new Color(0, 153, 51));
        rbtDpt.setSelected(false);
        txtDepartamento.setText("");
        txtCategoria.requestFocus();
    }//GEN-LAST:event_rbtCatActionPerformed

    private void Button_GuardarCatDptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarCatDptActionPerformed
        categoria.registrarCategoria();
//        if (role.equals("Admin")) {
        //guardarCatDpt();
//        } else {
//            JOptionPane.showMessageDialog(null, "No cuenta con el permiso requerido");
//        }
    }//GEN-LAST:event_Button_GuardarCatDptActionPerformed

    private void Button_EliminarCatDptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EliminarCatDptActionPerformed
//        if (role.equals("Admin")) {
//            eliminarDptoCat();
//        } else {
//            JOptionPane.showMessageDialog(null, "No cuenta con el permiso requerido");
//        }
    }//GEN-LAST:event_Button_EliminarCatDptActionPerformed

    private void Button_CancelarCatDptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarCatDptActionPerformed
        categoria.restablecer();
    }//GEN-LAST:event_Button_CancelarCatDptActionPerformed

    private void txtCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaKeyReleased
        if (txtCategoria.getText().isEmpty()) {
            lblCategoria.setText("Categoria");
            lblCategoria.setForeground(new Color(70, 106, 124));
        } else {
            lblCategoria.setText("Categoria");
            lblCategoria.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtCategoriaKeyReleased

    private void txtDepartamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepartamentoKeyReleased
        if (txtDepartamento.getText().isEmpty()) {
            lblDescripcion.setText("Departamento");
            lblDescripcion.setForeground(new Color(70, 106, 124));
        } else {
            lblDescripcion.setText("Departamento");
            lblDescripcion.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtDepartamentoKeyReleased

    private void tblDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDepartamentosMouseClicked
        if (tblDepartamentos.getSelectedRows().length > 0) {
            categoria.datosDpto();
        }
        
    }//GEN-LAST:event_tblDepartamentosMouseClicked

    private void tblDepartamentosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDepartamentosKeyReleased
        if (tblDepartamentos.getSelectedRows().length > 0) {
            categoria.datosDpto();
        }
    }//GEN-LAST:event_tblDepartamentosKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CancelarCatDpt;
    private javax.swing.JButton Button_EliminarCatDpt;
    private javax.swing.JButton Button_GuardarCatDpt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JRadioButton rbtCat;
    private javax.swing.JRadioButton rbtDpt;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTable tblDepartamentos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDepartamento;
    // End of variables declaration//GEN-END:variables

}
