/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Library.FormatDecimal;
import Library.Objetos;
import Library.TextFieldEvent;
import Models.Departamentos;
import ViewModels.ProductoVM;
import com.itextpdf.text.DocumentException;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author avice
 */
public class ProductosForm extends javax.swing.JInternalFrame {

    private ProductoVM producto;
    private Departamentos dptoProducto;
    public TextFieldEvent evento = new TextFieldEvent();
    public FormatDecimal formato = new FormatDecimal();

    /**
     * Creates new form ProductosForm
     */
    public ProductosForm() {
        initComponents();
        this.getContentPane().setBackground(new Color(101, 142, 173));

        ArrayList<JLabel> label = new ArrayList();
        label.add(lblImagenBarras);
        label.add(lblImagenProducto);

        ArrayList<JTextField> textfield = new ArrayList();
        textfield.add(txtBusquedaProductos);
        textfield.add(txtCodigoBarProdu);
        textfield.add(txtNombreProdu);
        textfield.add(txtStockProdu);
        textfield.add(txtStockMinProdu);
        textfield.add(txtPrecioCostoProdu);
        textfield.add(txtPrecioVentaProdu);
        textfield.add(txtUtilidadProdu);

        ArrayList<JTextArea> textArea = new ArrayList();
        textArea.add(txtDescripcionProdu);

        Object[] objects = {
            rbtCodigoProdu,
            rbtNombreProdu,
            rbtCategoriaProdu,
            tblProductos,
            cboDepartamentoProdu,
            cboCategoriaProdu,
            rbtActivoProdu,
            rbtInactivoProdu,};

        producto = new ProductoVM(objects, label, textfield, textArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupBuscar = new javax.swing.ButtonGroup();
        buttonGroupEstado = new javax.swing.ButtonGroup();
        TabbedPaneProductos = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        rbtCodigoProdu = new javax.swing.JRadioButton();
        rbtNombreProdu = new javax.swing.JRadioButton();
        rbtCategoriaProdu = new javax.swing.JRadioButton();
        txtBusquedaProductos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos =  tblProductos = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; // Disallow the editing of any cell
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoBarProdu = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();
        lblImagenBarras = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblImagenProducto = new javax.swing.JLabel();
        btnSeleccionarImagen = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        txtUtilidadProdu = new javax.swing.JTextField();
        txtPrecioVentaProdu = new javax.swing.JTextField();
        txtPrecioCostoProdu = new javax.swing.JTextField();
        txtStockMinProdu = new javax.swing.JTextField();
        txtStockProdu = new javax.swing.JTextField();
        rbtActivoProdu = new javax.swing.JRadioButton();
        rbtInactivoProdu = new javax.swing.JRadioButton();
        cboCategoriaProdu = new javax.swing.JComboBox();
        cboDepartamentoProdu = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionProdu = new javax.swing.JTextArea();
        txtNombreProdu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnImprimirCodigo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Productos");

        TabbedPaneProductos.setBackground(new java.awt.Color(233, 240, 248));

        jPanel2.setBackground(new java.awt.Color(233, 240, 248));

        rbtCodigoProdu.setBackground(new java.awt.Color(233, 240, 248));
        buttonGroupBuscar.add(rbtCodigoProdu);
        rbtCodigoProdu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtCodigoProdu.setText("Cód. Producto");
        rbtCodigoProdu.setOpaque(false);
        rbtCodigoProdu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtCodigoProduStateChanged(evt);
            }
        });

        rbtNombreProdu.setBackground(new java.awt.Color(233, 240, 248));
        buttonGroupBuscar.add(rbtNombreProdu);
        rbtNombreProdu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtNombreProdu.setText("Nombre");
        rbtNombreProdu.setOpaque(false);
        rbtNombreProdu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtNombreProduStateChanged(evt);
            }
        });

        rbtCategoriaProdu.setBackground(new java.awt.Color(233, 240, 248));
        buttonGroupBuscar.add(rbtCategoriaProdu);
        rbtCategoriaProdu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtCategoriaProdu.setText("Categoría");
        rbtCategoriaProdu.setOpaque(false);

        txtBusquedaProductos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtBusquedaProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaProductosKeyReleased(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(59, 69, 97));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-en-reporte-40.png"))); // NOI18N
        jButton3.setText("Reporte");

        tblProductos.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        tblProductos.setForeground(new java.awt.Color(102, 102, 255));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        tblProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtCodigoProdu)
                        .addGap(18, 18, 18)
                        .addComponent(rbtNombreProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbtCategoriaProdu))
                    .addComponent(txtBusquedaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtCodigoProdu)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbtNombreProdu)
                                .addComponent(rbtCategoriaProdu)))
                        .addGap(7, 7, 7)
                        .addComponent(txtBusquedaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPaneProductos.addTab("Buscar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(233, 240, 248));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Código de Barras:");

        txtCodigoBarProdu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodigoBarProdu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoBarProduKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoBarProduKeyTyped(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImagenBarras.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenBarras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenBarras, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImagenProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSeleccionarImagen.setBackground(new java.awt.Color(59, 69, 97));
        btnSeleccionarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-imagen-40.png"))); // NOI18N
        btnSeleccionarImagen.setToolTipText("Cargar imagen");
        btnSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagenActionPerformed(evt);
            }
        });

        btnCancelarProducto.setBackground(new java.awt.Color(59, 69, 97));
        btnCancelarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancelar_1.png"))); // NOI18N
        btnCancelarProducto.setToolTipText("Cancelar");
        btnCancelarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProductoActionPerformed(evt);
            }
        });

        btnAgregarProducto.setBackground(new java.awt.Color(59, 69, 97));
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Agregar_1.png"))); // NOI18N
        btnAgregarProducto.setToolTipText("Agregar");
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        txtUtilidadProdu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUtilidadProdu.setEnabled(false);
        txtUtilidadProdu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUtilidadProduKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUtilidadProduKeyTyped(evt);
            }
        });

        txtPrecioVentaProdu.setBackground(new java.awt.Color(254, 254, 241));
        txtPrecioVentaProdu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrecioVentaProdu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioVentaProduKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVentaProduKeyTyped(evt);
            }
        });

        txtPrecioCostoProdu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrecioCostoProdu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioCostoProduKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioCostoProduKeyTyped(evt);
            }
        });

        txtStockMinProdu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStockMinProdu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockMinProduKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockMinProduKeyTyped(evt);
            }
        });

        txtStockProdu.setBackground(new java.awt.Color(242, 253, 253));
        txtStockProdu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStockProdu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockProduKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockProduKeyTyped(evt);
            }
        });

        rbtActivoProdu.setBackground(new java.awt.Color(233, 240, 248));
        buttonGroupEstado.add(rbtActivoProdu);
        rbtActivoProdu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtActivoProdu.setSelected(true);
        rbtActivoProdu.setText("ACTIVO");

        rbtInactivoProdu.setBackground(new java.awt.Color(233, 240, 248));
        buttonGroupEstado.add(rbtInactivoProdu);
        rbtInactivoProdu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtInactivoProdu.setText("INACTIVO");

        cboDepartamentoProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDepartamentoProduActionPerformed(evt);
            }
        });

        txtDescripcionProdu.setColumns(20);
        txtDescripcionProdu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDescripcionProdu.setRows(5);
        jScrollPane3.setViewportView(txtDescripcionProdu);

        txtNombreProdu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNombreProdu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProduKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProduKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Departamento:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Categoría:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Estado:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Stock:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Stock Mínimo:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Precio Costo:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Precio Venta:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Utilidad:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("* Campos obligatorios");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("*");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("*");

        btnImprimirCodigo.setBackground(new java.awt.Color(59, 69, 97));
        btnImprimirCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-imprimir-32.png"))); // NOI18N
        btnImprimirCodigo.setToolTipText("Imprimir Código barras");
        btnImprimirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoBarProdu))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                        .addComponent(txtNombreProdu)
                                        .addComponent(cboCategoriaProdu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboDepartamentoProdu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtPrecioCostoProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioVentaProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUtilidadProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbtActivoProdu)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtInactivoProdu))
                                    .addComponent(txtStockProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStockMinProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnSeleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCancelarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(31, 31, 31)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnImprimirCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoBarProdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreProdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboDepartamentoProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCategoriaProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtActivoProdu)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtInactivoProdu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStockProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStockMinProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioCostoProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioVentaProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUtilidadProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TabbedPaneProductos.addTab("Nuevo / Modificar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabbedPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneProductos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoBarProduKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarProduKeyReleased
        if (txtCodigoBarProdu.getText().equals("")) {
            producto.codigo(lblImagenBarras, "0000000000000");
        } else {
            producto.codigo(lblImagenBarras, txtCodigoBarProdu.getText());
        }
    }//GEN-LAST:event_txtCodigoBarProduKeyReleased

    private void txtCodigoBarProduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarProduKeyTyped
        evento.numberKeyPress(evt);
    }//GEN-LAST:event_txtCodigoBarProduKeyTyped

    private void txtNombreProduKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProduKeyReleased
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER)
            txtDescripcionProdu.requestFocus();
    }//GEN-LAST:event_txtNombreProduKeyReleased

    private void txtNombreProduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProduKeyTyped
        txtNombreProdu.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNombreProduKeyTyped

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        Objetos.uploadImage.cargarImagen(lblImagenProducto, 260, 300);
        // TODO add your handling code here:
        //        String ruta = "";
        //        String pathOrigen;
        //        String pathDestino;
        //
        //        JFileChooser file = new JFileChooser();
        //        int estado = file.showOpenDialog(this);
        //        if (estado == JFileChooser.APPROVE_OPTION);
        //        {
        //            imagen = file.getSelectedFile().getName();
        //            //-----------------------------------------------
        //            pathOrigen = file.getSelectedFile().getAbsolutePath();
        //            pathDestino = "src/Images/" + imagen;
        //
        //            File origen = new File(pathOrigen);
        //            File destino = new File(pathDestino);
        //            try {
        //                InputStream in = new FileInputStream(origen);
        //                OutputStream out = new FileOutputStream(destino);
        //                byte[] buf = new byte[1024];
        //                int len;
        //
        //                while ((len = in.read(buf)) > 0) {
        //                    out.write(buf, 0, len);
        //                }
        //                in.close();
        //                out.close();
        //            } catch (IOException ex) {
        //                Logger.getLogger(FrmProducto.class.getName()).log(Level.SEVERE, null, ex);
        //            }
        //
        //            //-----------------------------------------------
        //            ruta = "src/Images/" + imagen;
        //            ImageIcon fot = new ImageIcon(ruta);
        //            Icon icono = new ImageIcon(fot.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
        //            lblImagen.setIcon(icono);
        //            lblImagen.repaint();
        //            //            ImageIcon img = new ImageIcon(ruta);
        //            //            lblImagen.setIcon(img);
        //            //            lblImagen.repaint();
        //            //System.out.println(ruta);
        //
        //        }
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void rbtCodigoProduStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtCodigoProduStateChanged
        txtBusquedaProductos.setText("");
    }//GEN-LAST:event_rbtCodigoProduStateChanged

    private void rbtNombreProduStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtNombreProduStateChanged
        txtBusquedaProductos.setText("");
    }//GEN-LAST:event_rbtNombreProduStateChanged

    private void txtBusquedaProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaProductosKeyReleased
        producto.searchProducto(txtBusquedaProductos.getText());
        producto.crearTabla();
        //        CantidadTotal();
    }//GEN-LAST:event_txtBusquedaProductosKeyReleased

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        producto.registrarProducto();
        TabbedPaneProductos.setSelectedIndex(0);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void txtStockProduKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockProduKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockProduKeyReleased

    private void txtStockProduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockProduKeyTyped
        evento.numberDecimalKeyPress(evt, txtStockProdu);
    }//GEN-LAST:event_txtStockProduKeyTyped

    private void txtStockMinProduKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockMinProduKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMinProduKeyReleased

    private void txtStockMinProduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockMinProduKeyTyped
        evento.numberDecimalKeyPress(evt, txtStockMinProdu);
    }//GEN-LAST:event_txtStockMinProduKeyTyped

    private void txtPrecioCostoProduKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCostoProduKeyReleased

    }//GEN-LAST:event_txtPrecioCostoProduKeyReleased

    private void txtPrecioCostoProduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCostoProduKeyTyped
        evento.numberDecimalKeyPress(evt, txtPrecioCostoProdu);
    }//GEN-LAST:event_txtPrecioCostoProduKeyTyped

    private void txtPrecioVentaProduKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaProduKeyReleased
        CalcularUtilidad();
    }//GEN-LAST:event_txtPrecioVentaProduKeyReleased

    private void txtPrecioVentaProduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaProduKeyTyped
        evento.numberDecimalKeyPress(evt, txtPrecioVentaProdu);
    }//GEN-LAST:event_txtPrecioVentaProduKeyTyped

    private void txtUtilidadProduKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUtilidadProduKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUtilidadProduKeyReleased

    private void txtUtilidadProduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUtilidadProduKeyTyped
        evento.numberDecimalKeyPress(evt, txtUtilidadProdu);
    }//GEN-LAST:event_txtUtilidadProduKeyTyped

    private void cboDepartamentoProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDepartamentoProduActionPerformed
        dptoProducto = (Departamentos) cboDepartamentoProdu.getSelectedItem();
        producto.getCategorias(cboDepartamentoProdu, cboCategoriaProdu,
                dptoProducto.getIdDpto(), "");
        //report.getProductos("");
    }//GEN-LAST:event_cboDepartamentoProduActionPerformed

    private void btnImprimirCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirCodigoActionPerformed
        try {
            producto.codeBarras(txtCodigoBarProdu.getText(), "Productos.pdf");
        } catch (DocumentException ex) {
            Logger.getLogger(ProductosForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirCodigoActionPerformed

    private void tblProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProductosKeyReleased
        if (tblProductos.getSelectedRows().length > 0) {
            producto.getProducto();
        }
    }//GEN-LAST:event_tblProductosKeyReleased

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        if (tblProductos.getSelectedRows().length > 0) {
            producto.getProducto();
            if (evt.getClickCount() == 2) {
                producto.getProducto();
                TabbedPaneProductos.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnCancelarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProductoActionPerformed
        producto.restablecer();
    }//GEN-LAST:event_btnCancelarProductoActionPerformed

    void CalcularUtilidad() {
        double pre_costo = 0, pre_venta = 0, utilidad = 0, t_utilidad;
        pre_costo = formato.reconstruir(txtPrecioCostoProdu.getText());
        pre_venta = formato.reconstruir(txtPrecioVentaProdu.getText());
        utilidad = pre_venta - pre_costo;
        t_utilidad = Math.rint(utilidad * 100) / 100;
        txtUtilidadProdu.setText(String.valueOf(formato.decimal(t_utilidad)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPaneProductos;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnImprimirCodigo;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.ButtonGroup buttonGroupBuscar;
    private javax.swing.ButtonGroup buttonGroupEstado;
    private javax.swing.JComboBox cboCategoriaProdu;
    private javax.swing.JComboBox cboDepartamentoProdu;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImagenBarras;
    private javax.swing.JLabel lblImagenProducto;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton rbtActivoProdu;
    private javax.swing.JRadioButton rbtCategoriaProdu;
    private javax.swing.JRadioButton rbtCodigoProdu;
    private javax.swing.JRadioButton rbtInactivoProdu;
    private javax.swing.JRadioButton rbtNombreProdu;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBusquedaProductos;
    private javax.swing.JTextField txtCodigoBarProdu;
    private javax.swing.JTextArea txtDescripcionProdu;
    private javax.swing.JTextField txtNombreProdu;
    private javax.swing.JTextField txtPrecioCostoProdu;
    private javax.swing.JTextField txtPrecioVentaProdu;
    private javax.swing.JTextField txtStockMinProdu;
    private javax.swing.JTextField txtStockProdu;
    private javax.swing.JTextField txtUtilidadProdu;
    // End of variables declaration//GEN-END:variables
}
