/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;

import Models.Proveedores;
import ViewModels.ProveedorVM;
import Views.ComprasForm;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author avice
 */
public class BuscarProveedorForm extends javax.swing.JInternalFrame {

    private ProveedorVM proveedor;
    private static int idProvee;

    /**
     * Creates new form BuscarProveedorForm
     */
    public BuscarProveedorForm() {
        initComponents();

        ArrayList<JLabel> label = new ArrayList();
        label.add(lblTotalRegistros);

        Object[] objects = {
            tblBuscarProv
        };

        proveedor = new ProveedorVM(objects, label);
        proveedor.searchProveedores("");
        proveedor.crearTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscarProv =  tblBuscarProv = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; // Disallow the editing of any cell
            }
        };
        txtBuscarProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSalirBuscarProv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalRegistros = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar Proveedor");
        setPreferredSize(new java.awt.Dimension(1056, 390));

        jPanel1.setBackground(new java.awt.Color(233, 240, 248));

        tblBuscarProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblBuscarProv.setSelectionBackground(new java.awt.Color(102, 204, 255));
        tblBuscarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscarProvMouseClicked(evt);
            }
        });
        tblBuscarProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblBuscarProvKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuscarProv);

        txtBuscarProveedor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtBuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarProveedorKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Buscar:");

        btnSalirBuscarProv.setBackground(new java.awt.Color(59, 69, 97));
        btnSalirBuscarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit32.png"))); // NOI18N
        btnSalirBuscarProv.setToolTipText("Salir");
        btnSalirBuscarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalirBuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirBuscarProvActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Registros:");

        lblTotalRegistros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnSalirBuscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalirBuscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalRegistros))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProveedorKeyTyped
        //        Objetos.eventos.textKeyPress(evt);
    }//GEN-LAST:event_txtBuscarProveedorKeyTyped

    private void btnSalirBuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirBuscarProvActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirBuscarProvActionPerformed

    private void txtBuscarProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProveedorKeyReleased
        proveedor.searchProveedores(txtBuscarProveedor.getText());
        proveedor.crearTabla();
    }//GEN-LAST:event_txtBuscarProveedorKeyReleased

    private void tblBuscarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscarProvMouseClicked
        if (tblBuscarProv.getSelectedRows().length > 0) {
            buscarProveedor();
        }
        if (evt.getClickCount() == 2) {
            buscarProveedor();
            this.dispose();
        }
    }//GEN-LAST:event_tblBuscarProvMouseClicked

    private void tblBuscarProvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBuscarProvKeyReleased
        if (tblBuscarProv.getSelectedRows().length > 0) {
            buscarProveedor();
        }
    }//GEN-LAST:event_tblBuscarProvKeyReleased

    private void buscarProveedor() {
        int fila;
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        fila = tblBuscarProv.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
        } else {
            defaultTableModel = (DefaultTableModel) tblBuscarProv.getModel();
            String nombre, apellidos, name;
            nombre = (String) defaultTableModel.getValueAt(fila, 1);
            apellidos = (String) defaultTableModel.getValueAt(fila, 2);
            name = nombre + " " + apellidos;

            idProvee = (Integer) defaultTableModel.getValueAt(fila, 0);
            if (name.equals(" ")) {
                ComprasForm.idProveedor = idProvee;
                ComprasForm.txtNombreProveedor.setText((String) defaultTableModel.getValueAt(fila, 3));
                ComprasForm.txtCodProveedor.setText((String) defaultTableModel.getValueAt(fila, 10));
            } else {
                ComprasForm.idProveedor = idProvee;
                ComprasForm.txtNombreProveedor.setText(name);
                ComprasForm.txtCodProveedor.setText((String) defaultTableModel.getValueAt(fila, 10));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirBuscarProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JTable tblBuscarProv;
    private javax.swing.JTextField txtBuscarProveedor;
    // End of variables declaration//GEN-END:variables
}
